### ISSUE TITLE
d6_theme() on windows + quarto markdwon

### ISSUE THREAD

**Issue by mariusgrabow** [EcoDynIZW/d6#3]
Hi,

I encountered a problem rendering quarto markdowns on Windows after using d6_theme(). Although the plots in the R Session show the custom font, rendering to HTML was impossible (via quarto) even though fonts are installed. The solution to this was a extrafont::loadfonts(device="win") **BEFORE** library(ggplot). It took me some time to find out, apparently this is a windows specific issue, but maybe we can add something like:

if(.Platform$OS.type == "windows") {extrafont::loadfonts(device="win")}

in the package. If there are no disadvantages in doing so, I could open a pull request.

Cheers, and cool theme,

Marius

**Comment by mariusgrabow** [comment]
(extrafont::loadfonts(device="win",quiet = T)) to suppress warnings

**Comment by wenzmo** [comment]
I added this to the funkction. Thank you Marius!!

**Comment by z3tt** [comment]
Hi @mariusgrabow, thanks for flagging this! IMO it is likely due to the different packages for font handling. As I always use {systemfonts} it works out of the box for me. Can you test that? 

I'll look into it once I am back from parental leave. Thanks @wenzmo for adding the {extrafont} line for now. I would love to avoid a dependency on that package though and also the sourcing of fonts when not using this package so I guess we need to finetune the code to make it work for everyone.

PS: It might be also a general setting you have to add to your qmd/rmd files? Not sure as I haven't used {extrafont} in years but for some packages like {showtext} I had to add that information in the chunk settings.

**Comment by z3tt** [comment]
Hi @mariusgrabow, as we have discussed using {systemfonts} might be the better solution here. I have, for now, removed the {extrafont} call from the theme again. And {systemfonts} is already part of the dependencies. 

Could you give it a try at some point (for now, creating plots locally should be enough as there other potential issues that can comde up when using rmd or qmd files) and let me know if it works? If it doesn't work, does loading the {systemfonts} package fix it? 

Thanks!

**Comment by mariusgrabow** [comment]
I still have problems using system fonts, it fails to find the font on all my computers despite being installed

**Comment by z3tt** [comment]
Just to make sure: it's systemfonts not sysfonts or smt similar? https://cran.r-project.org/web/packages/systemfonts/index.html

Are there any fonts listed if you run `systemfonts::system_fonts()`?

**Comment by mariusgrabow** [comment]
Yes, it is systemfonts. Running system_fonts() results in a long tibble (>500 rows), including PT Sans

**Comment by z3tt** [comment]
Solved: loading other font packages causes issues when using the systemfonts package (which is used in the theme).
